// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Character.proto

package com.seeker.treasure.model.player;

public final class Character {
  private Character() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code PlayerClass}
   */
  public enum PlayerClass
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>WARRIOR = 0;</code>
     */
    WARRIOR(0),
    /**
     * <code>HUNTER = 1;</code>
     */
    HUNTER(1),
    /**
     * <code>MAGE = 2;</code>
     */
    MAGE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>WARRIOR = 0;</code>
     */
    public static final int WARRIOR_VALUE = 0;
    /**
     * <code>HUNTER = 1;</code>
     */
    public static final int HUNTER_VALUE = 1;
    /**
     * <code>MAGE = 2;</code>
     */
    public static final int MAGE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PlayerClass valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static PlayerClass forNumber(int value) {
      switch (value) {
        case 0: return WARRIOR;
        case 1: return HUNTER;
        case 2: return MAGE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PlayerClass>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PlayerClass> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PlayerClass>() {
            public PlayerClass findValueByNumber(int number) {
              return PlayerClass.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.seeker.treasure.model.player.Character.getDescriptor().getEnumTypes().get(0);
    }

    private static final PlayerClass[] VALUES = values();

    public static PlayerClass valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PlayerClass(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PlayerClass)
  }

  public interface PlayerAvatarOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerAvatar)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.CharacterStatistics statistics = 3;</code>
     * @return Whether the statistics field is set.
     */
    boolean hasStatistics();
    /**
     * <code>.CharacterStatistics statistics = 3;</code>
     * @return The statistics.
     */
    com.seeker.treasure.model.player.Statistics.CharacterStatistics getStatistics();
    /**
     * <code>.CharacterStatistics statistics = 3;</code>
     */
    com.seeker.treasure.model.player.Statistics.CharacterStatisticsOrBuilder getStatisticsOrBuilder();

    /**
     * <code>.Experience experience = 4;</code>
     * @return Whether the experience field is set.
     */
    boolean hasExperience();
    /**
     * <code>.Experience experience = 4;</code>
     * @return The experience.
     */
    com.seeker.treasure.model.player.Statistics.Experience getExperience();
    /**
     * <code>.Experience experience = 4;</code>
     */
    com.seeker.treasure.model.player.Statistics.ExperienceOrBuilder getExperienceOrBuilder();

    /**
     * <code>.PlayerClass playerClass = 5;</code>
     * @return The enum numeric value on the wire for playerClass.
     */
    int getPlayerClassValue();
    /**
     * <code>.PlayerClass playerClass = 5;</code>
     * @return The playerClass.
     */
    com.seeker.treasure.model.player.Character.PlayerClass getPlayerClass();
  }
  /**
   * Protobuf type {@code PlayerAvatar}
   */
  public static final class PlayerAvatar extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlayerAvatar)
      PlayerAvatarOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerAvatar.newBuilder() to construct.
    private PlayerAvatar(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerAvatar() {
      name_ = "";
      playerClass_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayerAvatar();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerAvatar(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              com.seeker.treasure.model.player.Statistics.CharacterStatistics.Builder subBuilder = null;
              if (statistics_ != null) {
                subBuilder = statistics_.toBuilder();
              }
              statistics_ = input.readMessage(com.seeker.treasure.model.player.Statistics.CharacterStatistics.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(statistics_);
                statistics_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.seeker.treasure.model.player.Statistics.Experience.Builder subBuilder = null;
              if (experience_ != null) {
                subBuilder = experience_.toBuilder();
              }
              experience_ = input.readMessage(com.seeker.treasure.model.player.Statistics.Experience.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(experience_);
                experience_ = subBuilder.buildPartial();
              }

              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              playerClass_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.seeker.treasure.model.player.Character.internal_static_PlayerAvatar_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.seeker.treasure.model.player.Character.internal_static_PlayerAvatar_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.seeker.treasure.model.player.Character.PlayerAvatar.class, com.seeker.treasure.model.player.Character.PlayerAvatar.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATISTICS_FIELD_NUMBER = 3;
    private com.seeker.treasure.model.player.Statistics.CharacterStatistics statistics_;
    /**
     * <code>.CharacterStatistics statistics = 3;</code>
     * @return Whether the statistics field is set.
     */
    @java.lang.Override
    public boolean hasStatistics() {
      return statistics_ != null;
    }
    /**
     * <code>.CharacterStatistics statistics = 3;</code>
     * @return The statistics.
     */
    @java.lang.Override
    public com.seeker.treasure.model.player.Statistics.CharacterStatistics getStatistics() {
      return statistics_ == null ? com.seeker.treasure.model.player.Statistics.CharacterStatistics.getDefaultInstance() : statistics_;
    }
    /**
     * <code>.CharacterStatistics statistics = 3;</code>
     */
    @java.lang.Override
    public com.seeker.treasure.model.player.Statistics.CharacterStatisticsOrBuilder getStatisticsOrBuilder() {
      return getStatistics();
    }

    public static final int EXPERIENCE_FIELD_NUMBER = 4;
    private com.seeker.treasure.model.player.Statistics.Experience experience_;
    /**
     * <code>.Experience experience = 4;</code>
     * @return Whether the experience field is set.
     */
    @java.lang.Override
    public boolean hasExperience() {
      return experience_ != null;
    }
    /**
     * <code>.Experience experience = 4;</code>
     * @return The experience.
     */
    @java.lang.Override
    public com.seeker.treasure.model.player.Statistics.Experience getExperience() {
      return experience_ == null ? com.seeker.treasure.model.player.Statistics.Experience.getDefaultInstance() : experience_;
    }
    /**
     * <code>.Experience experience = 4;</code>
     */
    @java.lang.Override
    public com.seeker.treasure.model.player.Statistics.ExperienceOrBuilder getExperienceOrBuilder() {
      return getExperience();
    }

    public static final int PLAYERCLASS_FIELD_NUMBER = 5;
    private int playerClass_;
    /**
     * <code>.PlayerClass playerClass = 5;</code>
     * @return The enum numeric value on the wire for playerClass.
     */
    @java.lang.Override public int getPlayerClassValue() {
      return playerClass_;
    }
    /**
     * <code>.PlayerClass playerClass = 5;</code>
     * @return The playerClass.
     */
    @java.lang.Override public com.seeker.treasure.model.player.Character.PlayerClass getPlayerClass() {
      @SuppressWarnings("deprecation")
      com.seeker.treasure.model.player.Character.PlayerClass result = com.seeker.treasure.model.player.Character.PlayerClass.valueOf(playerClass_);
      return result == null ? com.seeker.treasure.model.player.Character.PlayerClass.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (statistics_ != null) {
        output.writeMessage(3, getStatistics());
      }
      if (experience_ != null) {
        output.writeMessage(4, getExperience());
      }
      if (playerClass_ != com.seeker.treasure.model.player.Character.PlayerClass.WARRIOR.getNumber()) {
        output.writeEnum(5, playerClass_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (statistics_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getStatistics());
      }
      if (experience_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getExperience());
      }
      if (playerClass_ != com.seeker.treasure.model.player.Character.PlayerClass.WARRIOR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, playerClass_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.seeker.treasure.model.player.Character.PlayerAvatar)) {
        return super.equals(obj);
      }
      com.seeker.treasure.model.player.Character.PlayerAvatar other = (com.seeker.treasure.model.player.Character.PlayerAvatar) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (hasStatistics() != other.hasStatistics()) return false;
      if (hasStatistics()) {
        if (!getStatistics()
            .equals(other.getStatistics())) return false;
      }
      if (hasExperience() != other.hasExperience()) return false;
      if (hasExperience()) {
        if (!getExperience()
            .equals(other.getExperience())) return false;
      }
      if (playerClass_ != other.playerClass_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasStatistics()) {
        hash = (37 * hash) + STATISTICS_FIELD_NUMBER;
        hash = (53 * hash) + getStatistics().hashCode();
      }
      if (hasExperience()) {
        hash = (37 * hash) + EXPERIENCE_FIELD_NUMBER;
        hash = (53 * hash) + getExperience().hashCode();
      }
      hash = (37 * hash) + PLAYERCLASS_FIELD_NUMBER;
      hash = (53 * hash) + playerClass_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.seeker.treasure.model.player.Character.PlayerAvatar parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeker.treasure.model.player.Character.PlayerAvatar parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeker.treasure.model.player.Character.PlayerAvatar parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeker.treasure.model.player.Character.PlayerAvatar parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeker.treasure.model.player.Character.PlayerAvatar parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeker.treasure.model.player.Character.PlayerAvatar parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeker.treasure.model.player.Character.PlayerAvatar parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seeker.treasure.model.player.Character.PlayerAvatar parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seeker.treasure.model.player.Character.PlayerAvatar parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.seeker.treasure.model.player.Character.PlayerAvatar parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seeker.treasure.model.player.Character.PlayerAvatar parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seeker.treasure.model.player.Character.PlayerAvatar parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.seeker.treasure.model.player.Character.PlayerAvatar prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerAvatar}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerAvatar)
        com.seeker.treasure.model.player.Character.PlayerAvatarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.seeker.treasure.model.player.Character.internal_static_PlayerAvatar_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.seeker.treasure.model.player.Character.internal_static_PlayerAvatar_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.seeker.treasure.model.player.Character.PlayerAvatar.class, com.seeker.treasure.model.player.Character.PlayerAvatar.Builder.class);
      }

      // Construct using com.seeker.treasure.model.player.Character.PlayerAvatar.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        if (statisticsBuilder_ == null) {
          statistics_ = null;
        } else {
          statistics_ = null;
          statisticsBuilder_ = null;
        }
        if (experienceBuilder_ == null) {
          experience_ = null;
        } else {
          experience_ = null;
          experienceBuilder_ = null;
        }
        playerClass_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.seeker.treasure.model.player.Character.internal_static_PlayerAvatar_descriptor;
      }

      @java.lang.Override
      public com.seeker.treasure.model.player.Character.PlayerAvatar getDefaultInstanceForType() {
        return com.seeker.treasure.model.player.Character.PlayerAvatar.getDefaultInstance();
      }

      @java.lang.Override
      public com.seeker.treasure.model.player.Character.PlayerAvatar build() {
        com.seeker.treasure.model.player.Character.PlayerAvatar result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.seeker.treasure.model.player.Character.PlayerAvatar buildPartial() {
        com.seeker.treasure.model.player.Character.PlayerAvatar result = new com.seeker.treasure.model.player.Character.PlayerAvatar(this);
        result.id_ = id_;
        result.name_ = name_;
        if (statisticsBuilder_ == null) {
          result.statistics_ = statistics_;
        } else {
          result.statistics_ = statisticsBuilder_.build();
        }
        if (experienceBuilder_ == null) {
          result.experience_ = experience_;
        } else {
          result.experience_ = experienceBuilder_.build();
        }
        result.playerClass_ = playerClass_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.seeker.treasure.model.player.Character.PlayerAvatar) {
          return mergeFrom((com.seeker.treasure.model.player.Character.PlayerAvatar)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.seeker.treasure.model.player.Character.PlayerAvatar other) {
        if (other == com.seeker.treasure.model.player.Character.PlayerAvatar.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hasStatistics()) {
          mergeStatistics(other.getStatistics());
        }
        if (other.hasExperience()) {
          mergeExperience(other.getExperience());
        }
        if (other.playerClass_ != 0) {
          setPlayerClassValue(other.getPlayerClassValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.seeker.treasure.model.player.Character.PlayerAvatar parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.seeker.treasure.model.player.Character.PlayerAvatar) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.seeker.treasure.model.player.Statistics.CharacterStatistics statistics_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.seeker.treasure.model.player.Statistics.CharacterStatistics, com.seeker.treasure.model.player.Statistics.CharacterStatistics.Builder, com.seeker.treasure.model.player.Statistics.CharacterStatisticsOrBuilder> statisticsBuilder_;
      /**
       * <code>.CharacterStatistics statistics = 3;</code>
       * @return Whether the statistics field is set.
       */
      public boolean hasStatistics() {
        return statisticsBuilder_ != null || statistics_ != null;
      }
      /**
       * <code>.CharacterStatistics statistics = 3;</code>
       * @return The statistics.
       */
      public com.seeker.treasure.model.player.Statistics.CharacterStatistics getStatistics() {
        if (statisticsBuilder_ == null) {
          return statistics_ == null ? com.seeker.treasure.model.player.Statistics.CharacterStatistics.getDefaultInstance() : statistics_;
        } else {
          return statisticsBuilder_.getMessage();
        }
      }
      /**
       * <code>.CharacterStatistics statistics = 3;</code>
       */
      public Builder setStatistics(com.seeker.treasure.model.player.Statistics.CharacterStatistics value) {
        if (statisticsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          statistics_ = value;
          onChanged();
        } else {
          statisticsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.CharacterStatistics statistics = 3;</code>
       */
      public Builder setStatistics(
          com.seeker.treasure.model.player.Statistics.CharacterStatistics.Builder builderForValue) {
        if (statisticsBuilder_ == null) {
          statistics_ = builderForValue.build();
          onChanged();
        } else {
          statisticsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.CharacterStatistics statistics = 3;</code>
       */
      public Builder mergeStatistics(com.seeker.treasure.model.player.Statistics.CharacterStatistics value) {
        if (statisticsBuilder_ == null) {
          if (statistics_ != null) {
            statistics_ =
              com.seeker.treasure.model.player.Statistics.CharacterStatistics.newBuilder(statistics_).mergeFrom(value).buildPartial();
          } else {
            statistics_ = value;
          }
          onChanged();
        } else {
          statisticsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.CharacterStatistics statistics = 3;</code>
       */
      public Builder clearStatistics() {
        if (statisticsBuilder_ == null) {
          statistics_ = null;
          onChanged();
        } else {
          statistics_ = null;
          statisticsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.CharacterStatistics statistics = 3;</code>
       */
      public com.seeker.treasure.model.player.Statistics.CharacterStatistics.Builder getStatisticsBuilder() {
        
        onChanged();
        return getStatisticsFieldBuilder().getBuilder();
      }
      /**
       * <code>.CharacterStatistics statistics = 3;</code>
       */
      public com.seeker.treasure.model.player.Statistics.CharacterStatisticsOrBuilder getStatisticsOrBuilder() {
        if (statisticsBuilder_ != null) {
          return statisticsBuilder_.getMessageOrBuilder();
        } else {
          return statistics_ == null ?
              com.seeker.treasure.model.player.Statistics.CharacterStatistics.getDefaultInstance() : statistics_;
        }
      }
      /**
       * <code>.CharacterStatistics statistics = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.seeker.treasure.model.player.Statistics.CharacterStatistics, com.seeker.treasure.model.player.Statistics.CharacterStatistics.Builder, com.seeker.treasure.model.player.Statistics.CharacterStatisticsOrBuilder> 
          getStatisticsFieldBuilder() {
        if (statisticsBuilder_ == null) {
          statisticsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.seeker.treasure.model.player.Statistics.CharacterStatistics, com.seeker.treasure.model.player.Statistics.CharacterStatistics.Builder, com.seeker.treasure.model.player.Statistics.CharacterStatisticsOrBuilder>(
                  getStatistics(),
                  getParentForChildren(),
                  isClean());
          statistics_ = null;
        }
        return statisticsBuilder_;
      }

      private com.seeker.treasure.model.player.Statistics.Experience experience_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.seeker.treasure.model.player.Statistics.Experience, com.seeker.treasure.model.player.Statistics.Experience.Builder, com.seeker.treasure.model.player.Statistics.ExperienceOrBuilder> experienceBuilder_;
      /**
       * <code>.Experience experience = 4;</code>
       * @return Whether the experience field is set.
       */
      public boolean hasExperience() {
        return experienceBuilder_ != null || experience_ != null;
      }
      /**
       * <code>.Experience experience = 4;</code>
       * @return The experience.
       */
      public com.seeker.treasure.model.player.Statistics.Experience getExperience() {
        if (experienceBuilder_ == null) {
          return experience_ == null ? com.seeker.treasure.model.player.Statistics.Experience.getDefaultInstance() : experience_;
        } else {
          return experienceBuilder_.getMessage();
        }
      }
      /**
       * <code>.Experience experience = 4;</code>
       */
      public Builder setExperience(com.seeker.treasure.model.player.Statistics.Experience value) {
        if (experienceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          experience_ = value;
          onChanged();
        } else {
          experienceBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Experience experience = 4;</code>
       */
      public Builder setExperience(
          com.seeker.treasure.model.player.Statistics.Experience.Builder builderForValue) {
        if (experienceBuilder_ == null) {
          experience_ = builderForValue.build();
          onChanged();
        } else {
          experienceBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Experience experience = 4;</code>
       */
      public Builder mergeExperience(com.seeker.treasure.model.player.Statistics.Experience value) {
        if (experienceBuilder_ == null) {
          if (experience_ != null) {
            experience_ =
              com.seeker.treasure.model.player.Statistics.Experience.newBuilder(experience_).mergeFrom(value).buildPartial();
          } else {
            experience_ = value;
          }
          onChanged();
        } else {
          experienceBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Experience experience = 4;</code>
       */
      public Builder clearExperience() {
        if (experienceBuilder_ == null) {
          experience_ = null;
          onChanged();
        } else {
          experience_ = null;
          experienceBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Experience experience = 4;</code>
       */
      public com.seeker.treasure.model.player.Statistics.Experience.Builder getExperienceBuilder() {
        
        onChanged();
        return getExperienceFieldBuilder().getBuilder();
      }
      /**
       * <code>.Experience experience = 4;</code>
       */
      public com.seeker.treasure.model.player.Statistics.ExperienceOrBuilder getExperienceOrBuilder() {
        if (experienceBuilder_ != null) {
          return experienceBuilder_.getMessageOrBuilder();
        } else {
          return experience_ == null ?
              com.seeker.treasure.model.player.Statistics.Experience.getDefaultInstance() : experience_;
        }
      }
      /**
       * <code>.Experience experience = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.seeker.treasure.model.player.Statistics.Experience, com.seeker.treasure.model.player.Statistics.Experience.Builder, com.seeker.treasure.model.player.Statistics.ExperienceOrBuilder> 
          getExperienceFieldBuilder() {
        if (experienceBuilder_ == null) {
          experienceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.seeker.treasure.model.player.Statistics.Experience, com.seeker.treasure.model.player.Statistics.Experience.Builder, com.seeker.treasure.model.player.Statistics.ExperienceOrBuilder>(
                  getExperience(),
                  getParentForChildren(),
                  isClean());
          experience_ = null;
        }
        return experienceBuilder_;
      }

      private int playerClass_ = 0;
      /**
       * <code>.PlayerClass playerClass = 5;</code>
       * @return The enum numeric value on the wire for playerClass.
       */
      @java.lang.Override public int getPlayerClassValue() {
        return playerClass_;
      }
      /**
       * <code>.PlayerClass playerClass = 5;</code>
       * @param value The enum numeric value on the wire for playerClass to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerClassValue(int value) {
        
        playerClass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.PlayerClass playerClass = 5;</code>
       * @return The playerClass.
       */
      @java.lang.Override
      public com.seeker.treasure.model.player.Character.PlayerClass getPlayerClass() {
        @SuppressWarnings("deprecation")
        com.seeker.treasure.model.player.Character.PlayerClass result = com.seeker.treasure.model.player.Character.PlayerClass.valueOf(playerClass_);
        return result == null ? com.seeker.treasure.model.player.Character.PlayerClass.UNRECOGNIZED : result;
      }
      /**
       * <code>.PlayerClass playerClass = 5;</code>
       * @param value The playerClass to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerClass(com.seeker.treasure.model.player.Character.PlayerClass value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        playerClass_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.PlayerClass playerClass = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerClass() {
        
        playerClass_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PlayerAvatar)
    }

    // @@protoc_insertion_point(class_scope:PlayerAvatar)
    private static final com.seeker.treasure.model.player.Character.PlayerAvatar DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.seeker.treasure.model.player.Character.PlayerAvatar();
    }

    public static com.seeker.treasure.model.player.Character.PlayerAvatar getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerAvatar>
        PARSER = new com.google.protobuf.AbstractParser<PlayerAvatar>() {
      @java.lang.Override
      public PlayerAvatar parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerAvatar(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerAvatar> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerAvatar> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.seeker.treasure.model.player.Character.PlayerAvatar getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerAvatar_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerAvatar_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Character.proto\032\020Statistics.proto\"\226\001\n\014" +
      "PlayerAvatar\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022(" +
      "\n\nstatistics\030\003 \001(\0132\024.CharacterStatistics" +
      "\022\037\n\nexperience\030\004 \001(\0132\013.Experience\022!\n\013pla" +
      "yerClass\030\005 \001(\0162\014.PlayerClass*0\n\013PlayerCl" +
      "ass\022\013\n\007WARRIOR\020\000\022\n\n\006HUNTER\020\001\022\010\n\004MAGE\020\002B-" +
      "\n com.seeker.treasure.model.playerB\tChar" +
      "acterb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.seeker.treasure.model.player.Statistics.getDescriptor(),
        });
    internal_static_PlayerAvatar_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PlayerAvatar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerAvatar_descriptor,
        new java.lang.String[] { "Id", "Name", "Statistics", "Experience", "PlayerClass", });
    com.seeker.treasure.model.player.Statistics.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
