// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Statistics.proto

package com.seeker.treasure.model.player;

public final class Statistics {
  private Statistics() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CharacterStatisticsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CharacterStatistics)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 hp = 2;</code>
     * @return The hp.
     */
    int getHp();

    /**
     * <code>int32 mana = 3;</code>
     * @return The mana.
     */
    int getMana();

    /**
     * <code>int32 strength = 4;</code>
     * @return The strength.
     */
    int getStrength();

    /**
     * <code>int32 dexterity = 5;</code>
     * @return The dexterity.
     */
    int getDexterity();

    /**
     * <code>int32 endurance = 6;</code>
     * @return The endurance.
     */
    int getEndurance();

    /**
     * <code>int32 intelligence = 7;</code>
     * @return The intelligence.
     */
    int getIntelligence();

    /**
     * <code>int32 charisma = 8;</code>
     * @return The charisma.
     */
    int getCharisma();
  }
  /**
   * Protobuf type {@code CharacterStatistics}
   */
  public static final class CharacterStatistics extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CharacterStatistics)
      CharacterStatisticsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CharacterStatistics.newBuilder() to construct.
    private CharacterStatistics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CharacterStatistics() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CharacterStatistics();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CharacterStatistics(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 16: {

              hp_ = input.readInt32();
              break;
            }
            case 24: {

              mana_ = input.readInt32();
              break;
            }
            case 32: {

              strength_ = input.readInt32();
              break;
            }
            case 40: {

              dexterity_ = input.readInt32();
              break;
            }
            case 48: {

              endurance_ = input.readInt32();
              break;
            }
            case 56: {

              intelligence_ = input.readInt32();
              break;
            }
            case 64: {

              charisma_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.seeker.treasure.model.player.Statistics.internal_static_CharacterStatistics_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.seeker.treasure.model.player.Statistics.internal_static_CharacterStatistics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.seeker.treasure.model.player.Statistics.CharacterStatistics.class, com.seeker.treasure.model.player.Statistics.CharacterStatistics.Builder.class);
    }

    public static final int HP_FIELD_NUMBER = 2;
    private int hp_;
    /**
     * <code>int32 hp = 2;</code>
     * @return The hp.
     */
    @java.lang.Override
    public int getHp() {
      return hp_;
    }

    public static final int MANA_FIELD_NUMBER = 3;
    private int mana_;
    /**
     * <code>int32 mana = 3;</code>
     * @return The mana.
     */
    @java.lang.Override
    public int getMana() {
      return mana_;
    }

    public static final int STRENGTH_FIELD_NUMBER = 4;
    private int strength_;
    /**
     * <code>int32 strength = 4;</code>
     * @return The strength.
     */
    @java.lang.Override
    public int getStrength() {
      return strength_;
    }

    public static final int DEXTERITY_FIELD_NUMBER = 5;
    private int dexterity_;
    /**
     * <code>int32 dexterity = 5;</code>
     * @return The dexterity.
     */
    @java.lang.Override
    public int getDexterity() {
      return dexterity_;
    }

    public static final int ENDURANCE_FIELD_NUMBER = 6;
    private int endurance_;
    /**
     * <code>int32 endurance = 6;</code>
     * @return The endurance.
     */
    @java.lang.Override
    public int getEndurance() {
      return endurance_;
    }

    public static final int INTELLIGENCE_FIELD_NUMBER = 7;
    private int intelligence_;
    /**
     * <code>int32 intelligence = 7;</code>
     * @return The intelligence.
     */
    @java.lang.Override
    public int getIntelligence() {
      return intelligence_;
    }

    public static final int CHARISMA_FIELD_NUMBER = 8;
    private int charisma_;
    /**
     * <code>int32 charisma = 8;</code>
     * @return The charisma.
     */
    @java.lang.Override
    public int getCharisma() {
      return charisma_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hp_ != 0) {
        output.writeInt32(2, hp_);
      }
      if (mana_ != 0) {
        output.writeInt32(3, mana_);
      }
      if (strength_ != 0) {
        output.writeInt32(4, strength_);
      }
      if (dexterity_ != 0) {
        output.writeInt32(5, dexterity_);
      }
      if (endurance_ != 0) {
        output.writeInt32(6, endurance_);
      }
      if (intelligence_ != 0) {
        output.writeInt32(7, intelligence_);
      }
      if (charisma_ != 0) {
        output.writeInt32(8, charisma_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (hp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, hp_);
      }
      if (mana_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, mana_);
      }
      if (strength_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, strength_);
      }
      if (dexterity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, dexterity_);
      }
      if (endurance_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, endurance_);
      }
      if (intelligence_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, intelligence_);
      }
      if (charisma_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, charisma_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.seeker.treasure.model.player.Statistics.CharacterStatistics)) {
        return super.equals(obj);
      }
      com.seeker.treasure.model.player.Statistics.CharacterStatistics other = (com.seeker.treasure.model.player.Statistics.CharacterStatistics) obj;

      if (getHp()
          != other.getHp()) return false;
      if (getMana()
          != other.getMana()) return false;
      if (getStrength()
          != other.getStrength()) return false;
      if (getDexterity()
          != other.getDexterity()) return false;
      if (getEndurance()
          != other.getEndurance()) return false;
      if (getIntelligence()
          != other.getIntelligence()) return false;
      if (getCharisma()
          != other.getCharisma()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HP_FIELD_NUMBER;
      hash = (53 * hash) + getHp();
      hash = (37 * hash) + MANA_FIELD_NUMBER;
      hash = (53 * hash) + getMana();
      hash = (37 * hash) + STRENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getStrength();
      hash = (37 * hash) + DEXTERITY_FIELD_NUMBER;
      hash = (53 * hash) + getDexterity();
      hash = (37 * hash) + ENDURANCE_FIELD_NUMBER;
      hash = (53 * hash) + getEndurance();
      hash = (37 * hash) + INTELLIGENCE_FIELD_NUMBER;
      hash = (53 * hash) + getIntelligence();
      hash = (37 * hash) + CHARISMA_FIELD_NUMBER;
      hash = (53 * hash) + getCharisma();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.seeker.treasure.model.player.Statistics.CharacterStatistics parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeker.treasure.model.player.Statistics.CharacterStatistics parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeker.treasure.model.player.Statistics.CharacterStatistics parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeker.treasure.model.player.Statistics.CharacterStatistics parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeker.treasure.model.player.Statistics.CharacterStatistics parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeker.treasure.model.player.Statistics.CharacterStatistics parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeker.treasure.model.player.Statistics.CharacterStatistics parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seeker.treasure.model.player.Statistics.CharacterStatistics parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seeker.treasure.model.player.Statistics.CharacterStatistics parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.seeker.treasure.model.player.Statistics.CharacterStatistics parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seeker.treasure.model.player.Statistics.CharacterStatistics parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seeker.treasure.model.player.Statistics.CharacterStatistics parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.seeker.treasure.model.player.Statistics.CharacterStatistics prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CharacterStatistics}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CharacterStatistics)
        com.seeker.treasure.model.player.Statistics.CharacterStatisticsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.seeker.treasure.model.player.Statistics.internal_static_CharacterStatistics_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.seeker.treasure.model.player.Statistics.internal_static_CharacterStatistics_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.seeker.treasure.model.player.Statistics.CharacterStatistics.class, com.seeker.treasure.model.player.Statistics.CharacterStatistics.Builder.class);
      }

      // Construct using com.seeker.treasure.model.player.Statistics.CharacterStatistics.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        hp_ = 0;

        mana_ = 0;

        strength_ = 0;

        dexterity_ = 0;

        endurance_ = 0;

        intelligence_ = 0;

        charisma_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.seeker.treasure.model.player.Statistics.internal_static_CharacterStatistics_descriptor;
      }

      @java.lang.Override
      public com.seeker.treasure.model.player.Statistics.CharacterStatistics getDefaultInstanceForType() {
        return com.seeker.treasure.model.player.Statistics.CharacterStatistics.getDefaultInstance();
      }

      @java.lang.Override
      public com.seeker.treasure.model.player.Statistics.CharacterStatistics build() {
        com.seeker.treasure.model.player.Statistics.CharacterStatistics result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.seeker.treasure.model.player.Statistics.CharacterStatistics buildPartial() {
        com.seeker.treasure.model.player.Statistics.CharacterStatistics result = new com.seeker.treasure.model.player.Statistics.CharacterStatistics(this);
        result.hp_ = hp_;
        result.mana_ = mana_;
        result.strength_ = strength_;
        result.dexterity_ = dexterity_;
        result.endurance_ = endurance_;
        result.intelligence_ = intelligence_;
        result.charisma_ = charisma_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.seeker.treasure.model.player.Statistics.CharacterStatistics) {
          return mergeFrom((com.seeker.treasure.model.player.Statistics.CharacterStatistics)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.seeker.treasure.model.player.Statistics.CharacterStatistics other) {
        if (other == com.seeker.treasure.model.player.Statistics.CharacterStatistics.getDefaultInstance()) return this;
        if (other.getHp() != 0) {
          setHp(other.getHp());
        }
        if (other.getMana() != 0) {
          setMana(other.getMana());
        }
        if (other.getStrength() != 0) {
          setStrength(other.getStrength());
        }
        if (other.getDexterity() != 0) {
          setDexterity(other.getDexterity());
        }
        if (other.getEndurance() != 0) {
          setEndurance(other.getEndurance());
        }
        if (other.getIntelligence() != 0) {
          setIntelligence(other.getIntelligence());
        }
        if (other.getCharisma() != 0) {
          setCharisma(other.getCharisma());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.seeker.treasure.model.player.Statistics.CharacterStatistics parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.seeker.treasure.model.player.Statistics.CharacterStatistics) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int hp_ ;
      /**
       * <code>int32 hp = 2;</code>
       * @return The hp.
       */
      @java.lang.Override
      public int getHp() {
        return hp_;
      }
      /**
       * <code>int32 hp = 2;</code>
       * @param value The hp to set.
       * @return This builder for chaining.
       */
      public Builder setHp(int value) {
        
        hp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 hp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHp() {
        
        hp_ = 0;
        onChanged();
        return this;
      }

      private int mana_ ;
      /**
       * <code>int32 mana = 3;</code>
       * @return The mana.
       */
      @java.lang.Override
      public int getMana() {
        return mana_;
      }
      /**
       * <code>int32 mana = 3;</code>
       * @param value The mana to set.
       * @return This builder for chaining.
       */
      public Builder setMana(int value) {
        
        mana_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 mana = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMana() {
        
        mana_ = 0;
        onChanged();
        return this;
      }

      private int strength_ ;
      /**
       * <code>int32 strength = 4;</code>
       * @return The strength.
       */
      @java.lang.Override
      public int getStrength() {
        return strength_;
      }
      /**
       * <code>int32 strength = 4;</code>
       * @param value The strength to set.
       * @return This builder for chaining.
       */
      public Builder setStrength(int value) {
        
        strength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 strength = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStrength() {
        
        strength_ = 0;
        onChanged();
        return this;
      }

      private int dexterity_ ;
      /**
       * <code>int32 dexterity = 5;</code>
       * @return The dexterity.
       */
      @java.lang.Override
      public int getDexterity() {
        return dexterity_;
      }
      /**
       * <code>int32 dexterity = 5;</code>
       * @param value The dexterity to set.
       * @return This builder for chaining.
       */
      public Builder setDexterity(int value) {
        
        dexterity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dexterity = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDexterity() {
        
        dexterity_ = 0;
        onChanged();
        return this;
      }

      private int endurance_ ;
      /**
       * <code>int32 endurance = 6;</code>
       * @return The endurance.
       */
      @java.lang.Override
      public int getEndurance() {
        return endurance_;
      }
      /**
       * <code>int32 endurance = 6;</code>
       * @param value The endurance to set.
       * @return This builder for chaining.
       */
      public Builder setEndurance(int value) {
        
        endurance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 endurance = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndurance() {
        
        endurance_ = 0;
        onChanged();
        return this;
      }

      private int intelligence_ ;
      /**
       * <code>int32 intelligence = 7;</code>
       * @return The intelligence.
       */
      @java.lang.Override
      public int getIntelligence() {
        return intelligence_;
      }
      /**
       * <code>int32 intelligence = 7;</code>
       * @param value The intelligence to set.
       * @return This builder for chaining.
       */
      public Builder setIntelligence(int value) {
        
        intelligence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 intelligence = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearIntelligence() {
        
        intelligence_ = 0;
        onChanged();
        return this;
      }

      private int charisma_ ;
      /**
       * <code>int32 charisma = 8;</code>
       * @return The charisma.
       */
      @java.lang.Override
      public int getCharisma() {
        return charisma_;
      }
      /**
       * <code>int32 charisma = 8;</code>
       * @param value The charisma to set.
       * @return This builder for chaining.
       */
      public Builder setCharisma(int value) {
        
        charisma_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 charisma = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearCharisma() {
        
        charisma_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CharacterStatistics)
    }

    // @@protoc_insertion_point(class_scope:CharacterStatistics)
    private static final com.seeker.treasure.model.player.Statistics.CharacterStatistics DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.seeker.treasure.model.player.Statistics.CharacterStatistics();
    }

    public static com.seeker.treasure.model.player.Statistics.CharacterStatistics getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CharacterStatistics>
        PARSER = new com.google.protobuf.AbstractParser<CharacterStatistics>() {
      @java.lang.Override
      public CharacterStatistics parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CharacterStatistics(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CharacterStatistics> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CharacterStatistics> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.seeker.treasure.model.player.Statistics.CharacterStatistics getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ExperienceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Experience)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 level = 1;</code>
     * @return The level.
     */
    int getLevel();

    /**
     * <code>int64 experience = 2;</code>
     * @return The experience.
     */
    long getExperience();
  }
  /**
   * Protobuf type {@code Experience}
   */
  public static final class Experience extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Experience)
      ExperienceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Experience.newBuilder() to construct.
    private Experience(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Experience() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Experience();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Experience(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              level_ = input.readInt32();
              break;
            }
            case 16: {

              experience_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.seeker.treasure.model.player.Statistics.internal_static_Experience_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.seeker.treasure.model.player.Statistics.internal_static_Experience_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.seeker.treasure.model.player.Statistics.Experience.class, com.seeker.treasure.model.player.Statistics.Experience.Builder.class);
    }

    public static final int LEVEL_FIELD_NUMBER = 1;
    private int level_;
    /**
     * <code>int32 level = 1;</code>
     * @return The level.
     */
    @java.lang.Override
    public int getLevel() {
      return level_;
    }

    public static final int EXPERIENCE_FIELD_NUMBER = 2;
    private long experience_;
    /**
     * <code>int64 experience = 2;</code>
     * @return The experience.
     */
    @java.lang.Override
    public long getExperience() {
      return experience_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (level_ != 0) {
        output.writeInt32(1, level_);
      }
      if (experience_ != 0L) {
        output.writeInt64(2, experience_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (level_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, level_);
      }
      if (experience_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, experience_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.seeker.treasure.model.player.Statistics.Experience)) {
        return super.equals(obj);
      }
      com.seeker.treasure.model.player.Statistics.Experience other = (com.seeker.treasure.model.player.Statistics.Experience) obj;

      if (getLevel()
          != other.getLevel()) return false;
      if (getExperience()
          != other.getExperience()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel();
      hash = (37 * hash) + EXPERIENCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExperience());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.seeker.treasure.model.player.Statistics.Experience parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeker.treasure.model.player.Statistics.Experience parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeker.treasure.model.player.Statistics.Experience parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeker.treasure.model.player.Statistics.Experience parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeker.treasure.model.player.Statistics.Experience parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seeker.treasure.model.player.Statistics.Experience parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seeker.treasure.model.player.Statistics.Experience parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seeker.treasure.model.player.Statistics.Experience parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seeker.treasure.model.player.Statistics.Experience parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.seeker.treasure.model.player.Statistics.Experience parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.seeker.treasure.model.player.Statistics.Experience parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.seeker.treasure.model.player.Statistics.Experience parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.seeker.treasure.model.player.Statistics.Experience prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Experience}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Experience)
        com.seeker.treasure.model.player.Statistics.ExperienceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.seeker.treasure.model.player.Statistics.internal_static_Experience_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.seeker.treasure.model.player.Statistics.internal_static_Experience_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.seeker.treasure.model.player.Statistics.Experience.class, com.seeker.treasure.model.player.Statistics.Experience.Builder.class);
      }

      // Construct using com.seeker.treasure.model.player.Statistics.Experience.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        level_ = 0;

        experience_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.seeker.treasure.model.player.Statistics.internal_static_Experience_descriptor;
      }

      @java.lang.Override
      public com.seeker.treasure.model.player.Statistics.Experience getDefaultInstanceForType() {
        return com.seeker.treasure.model.player.Statistics.Experience.getDefaultInstance();
      }

      @java.lang.Override
      public com.seeker.treasure.model.player.Statistics.Experience build() {
        com.seeker.treasure.model.player.Statistics.Experience result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.seeker.treasure.model.player.Statistics.Experience buildPartial() {
        com.seeker.treasure.model.player.Statistics.Experience result = new com.seeker.treasure.model.player.Statistics.Experience(this);
        result.level_ = level_;
        result.experience_ = experience_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.seeker.treasure.model.player.Statistics.Experience) {
          return mergeFrom((com.seeker.treasure.model.player.Statistics.Experience)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.seeker.treasure.model.player.Statistics.Experience other) {
        if (other == com.seeker.treasure.model.player.Statistics.Experience.getDefaultInstance()) return this;
        if (other.getLevel() != 0) {
          setLevel(other.getLevel());
        }
        if (other.getExperience() != 0L) {
          setExperience(other.getExperience());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.seeker.treasure.model.player.Statistics.Experience parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.seeker.treasure.model.player.Statistics.Experience) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int level_ ;
      /**
       * <code>int32 level = 1;</code>
       * @return The level.
       */
      @java.lang.Override
      public int getLevel() {
        return level_;
      }
      /**
       * <code>int32 level = 1;</code>
       * @param value The level to set.
       * @return This builder for chaining.
       */
      public Builder setLevel(int value) {
        
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 level = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLevel() {
        
        level_ = 0;
        onChanged();
        return this;
      }

      private long experience_ ;
      /**
       * <code>int64 experience = 2;</code>
       * @return The experience.
       */
      @java.lang.Override
      public long getExperience() {
        return experience_;
      }
      /**
       * <code>int64 experience = 2;</code>
       * @param value The experience to set.
       * @return This builder for chaining.
       */
      public Builder setExperience(long value) {
        
        experience_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 experience = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearExperience() {
        
        experience_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Experience)
    }

    // @@protoc_insertion_point(class_scope:Experience)
    private static final com.seeker.treasure.model.player.Statistics.Experience DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.seeker.treasure.model.player.Statistics.Experience();
    }

    public static com.seeker.treasure.model.player.Statistics.Experience getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Experience>
        PARSER = new com.google.protobuf.AbstractParser<Experience>() {
      @java.lang.Override
      public Experience parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Experience(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Experience> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Experience> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.seeker.treasure.model.player.Statistics.Experience getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CharacterStatistics_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CharacterStatistics_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Experience_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Experience_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Statistics.proto\"\217\001\n\023CharacterStatisti" +
      "cs\022\n\n\002hp\030\002 \001(\005\022\014\n\004mana\030\003 \001(\005\022\020\n\010strength" +
      "\030\004 \001(\005\022\021\n\tdexterity\030\005 \001(\005\022\021\n\tendurance\030\006" +
      " \001(\005\022\024\n\014intelligence\030\007 \001(\005\022\020\n\010charisma\030\010" +
      " \001(\005\"/\n\nExperience\022\r\n\005level\030\001 \001(\005\022\022\n\nexp" +
      "erience\030\002 \001(\003B.\n com.seeker.treasure.mod" +
      "el.playerB\nStatisticsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CharacterStatistics_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CharacterStatistics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CharacterStatistics_descriptor,
        new java.lang.String[] { "Hp", "Mana", "Strength", "Dexterity", "Endurance", "Intelligence", "Charisma", });
    internal_static_Experience_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Experience_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Experience_descriptor,
        new java.lang.String[] { "Level", "Experience", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
